###


###


GET http://localhost:3000/usuarios


###


POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "helena",
    "senha": "12345",
    "email": "helena_bequi@estudante.sesisenai.org.br"
}


###


PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "helena",
    "senha": "12345",
    "email": "helena_bequi@estudante.sesisenai.org.br"
}

###


DELETE http://localhost:3000/usuarios/1

###
 
POST http://localhost:3000/login
Content-Type: application/json

{
    "senha": "12345",
    "email": "helena_bequi@estudante.sesisenai.org.br"
}


###